---
mongo:
  host: '127.0.0.1'
  port: '27017'
  db: "cibyl"

jobs:
  - name: hello_world
    label: Hello World
    description: "Just a job... with a job's courage"

  - name: hello_world2
    label: Hello World Again
    description: "Nothing but the pure of heart!"

  - name: hello_world3
    label: Hello World Thrice - no desc

repos:
  - name: user-interface
  - name: dxansible
  - name: warehouse
