// Generated by CoffeeScript 1.6.3
(function() {
  var Job, assert;

  Job = require('../app/models').Job;

  assert = require('assert');

  exports.jobs = {
    get: function(req, res) {
      return Job.findOne({
        'name': req.params.job_name
      }, function(err, job) {
        return res.send({
          "job": job
        });
      });
    },
    run: function(req, res) {
      return Job.findOne({
        'name': req.params.job_name
      }, function(err, job) {
        var unbusy;
        res.send({
          "job": job
        });
        res.send({
          "success": true
        });
        job.set('busy', true);
        job.save(function(err) {
          return assert.ifError(err);
        });
        unbusy = function() {
          job.set('busy', false);
          return job.save(function(err) {
            return assert.ifError(err);
          });
        };
        return setTimeout(unbusy, 5000);
      });
    }
  };

}).call(this);
