// Generated by CoffeeScript 1.6.3
(function() {
  var Repo, assert;

  Repo = require('../app/models').Repo;

  assert = require('assert');

  exports.repos = {
    get: function(req, res) {
      return Repo.find(function(err, repos) {
        return res.send({
          "repos": repos
        });
      });
    }
  };

}).call(this);
