// Generated by CoffeeScript 1.6.3
(function() {
  var job_schema, mongoose, repo_schema;

  mongoose = require('mongoose');

  mongoose.connect('mongodb://localhost/cibyl');

  repo_schema = mongoose.Schema({
    name: String
  });

  job_schema = mongoose.Schema({
    name: String,
    label: String,
    description: String
  });

  exports.Repo = mongoose.model('Repo', repo_schema);

  exports.Job = mongoose.model('Job', job_schema);

}).call(this);
